"use client";
import { useState } from "react";
import { deleteTask, updateTask } from "@/app/actions/task";
import { getUsersForAssignment } from "@/app/actions/task";
import ConfirmDialog from "@/components/ConfirmDialog";
import { Pencil, Trash2, X } from "@/components/icons";

type Task={id:string;title:string;description:string;status:"todo"|"in-progress"|"done";priority:"low"|"medium"|"high";dueDate?:string|null;assignees:string[];tags:string[];workspaceId:string;isOwner:boolean};
type User={name:string;email:string};
export default function TaskActions({task,onDone,afterDelete}:{task:Task;onDone?:()=>void;afterDelete?:()=>void}){const [edit,setEdit]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[users,setUsers]=useState<User[]>([]),[selected,setSelected]=useState(task.assignees||[]),[error,setError]=useState("");
 async function openEdit(){const r=await getUsersForAssignment(task.workspaceId);if(r.success)setUsers(r.users);setSelected(task.assignees||[]);setEdit(true)}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const r=await updateTask(task.id,{workspaceId:task.workspaceId,title:String(fd.get("title")||""),description:String(fd.get("description")||""),status:String(fd.get("status")||task.status),priority:String(fd.get("priority")||task.priority),dueDate:String(fd.get("dueDate")||"")||null,assignees:selected,tags:String(fd.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean)});setBusy(false);if(!r.success){setError(r.message||"Update failed");return}setEdit(false);onDone?.()}
 async function remove(){setBusy(true);const r=await deleteTask(task.id);setBusy(false);setConfirm(false);if(r.success){(afterDelete||(()=>window.location.href="/dashboard"))()}else setError(r.message||"Delete failed")}
 if(!task.isOwner)return null;
 return <>{<div className="flex gap-1"><button className="icon-button" title="Edit task" onClick={openEdit}><Pencil size={16}/></button><button className="icon-button text-rose-500" title="Delete task" onClick={()=>setConfirm(true)}><Trash2 size={16}/></button></div>}{edit&&<div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><h2 className="text-lg font-bold">Edit task</h2><p className="mt-1 text-xs muted">Update task details and assignment.</p></div><button className="icon-button" onClick={()=>setEdit(false)}><X size={19}/></button></div><form className="modal-body" onSubmit={save}><div className="form-grid"><div className="field-full"><label className="label">Title *</label><input name="title" defaultValue={task.title} className="input" required maxLength={100}/></div><div className="field-full"><label className="label">Description</label><textarea name="description" defaultValue={task.description} className="textarea" maxLength={2000}/></div><div><label className="label">Status</label><select name="status" defaultValue={task.status} className="select"><option value="todo">To Do</option><option value="in-progress">In Progress</option><option value="done">Completed</option></select></div><div><label className="label">Priority</label><select name="priority" defaultValue={task.priority} className="select"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div><label className="label">Due date</label><input name="dueDate" type="date" defaultValue={task.dueDate||""} className="input"/></div><div><label className="label">Assignees</label><div className="max-h-32 overflow-auto rounded-lg border border-[var(--border)] p-2">{users.map(u=><label key={u.email} className="dropdown-item"><input type="checkbox" checked={selected.includes(u.email)} onChange={()=>setSelected(v=>v.includes(u.email)?v.filter(x=>x!==u.email):[...v,u.email])}/>{u.name}<span className="ml-auto text-[10px] muted">{u.email}</span></label>)}</div></div><div className="field-full"><label className="label">Tags</label><input name="tags" defaultValue={task.tags.join(", ")} className="input"/></div></div>{error&&<p className="mt-3 text-xs text-rose-500">{error}</p>}<div className="modal-footer"><button type="button" className="button button-secondary" onClick={()=>setEdit(false)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy?"Saving...":"Save changes"}</button></div></form></div></div>}<ConfirmDialog open={confirm} title="Delete this task?" description="This permanently removes the task and its comments. This action cannot be undone." confirmLabel="Delete task" busy={busy} onCancel={()=>setConfirm(false)} onConfirm={remove}/></>;
}
