"use server";
import { ObjectId } from "mongodb";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { getDb } from "@/lib/mongodb";
import { taskSchema } from "@/lib/validations/task";
import { getAllUsers } from "@/lib/user";
const statusOrder=["todo","in-progress","done"] as const;
type Status=typeof statusOrder[number];
function access(taskId:string,email:string){return{_id:new ObjectId(taskId),$or:[{createdBy:email},{assignees:email},{assignee:email}]}};
async function workspaceFor(db:any,id:string,email:string){if(!ObjectId.isValid(id))return null;return db.collection("workspaces").findOne({_id:new ObjectId(id),"members.email":email});}
async function validateAssignees(db:any,workspaceId:string,assignees:string[]){const normalized=Array.from(new Set(assignees.map(e=>e.trim().toLowerCase()).filter(Boolean)));if(!normalized.length)return{success:true as const,assignees:[] as string[]};const w=await db.collection("workspaces").findOne({_id:new ObjectId(workspaceId),"members.email":{$in:normalized}});if(!w)return{success:false as const,message:"One or more assignees are not members of this workspace"};const members=new Set((w.members||[]).map((m:any)=>m.email));const invalid=normalized.filter(e=>!members.has(e));if(invalid.length)return{success:false as const,message:"One or more assignees are not members of this workspace"};return{success:true as const,assignees:normalized};}
async function notify(db:any,userEmail:string,title:string,message:string,href:string){await db.collection("notifications").insertOne({userEmail,title,message,href,type:"task",read:false,createdAt:new Date()})}
export async function createTask(input:unknown){try{const s=await auth();if(!s?.user?.email)return{success:false,message:"You must be logged in"};const p=taskSchema.safeParse(input);if(!p.success)return{success:false,message:p.error.issues[0]?.message||"Invalid task data",errors:p.error.flatten().fieldErrors};const workspaceId=String((input as any)?.workspaceId||"");if(!ObjectId.isValid(workspaceId))return{success:false,message:"Choose a valid workspace"};const db=await getDb();const w=await workspaceFor(db,workspaceId,s.user.email);if(!w)return{success:false,message:"You are not a member of this workspace"};const av=await validateAssignees(db,workspaceId,p.data.assignees);if(!av.success)return av;const tags=Array.from(new Set(p.data.tags.map(x=>x.trim()).filter(Boolean)));const now=new Date();const task={...p.data,workspaceId:new ObjectId(workspaceId),assignees:av.assignees,tags,createdBy:s.user.email,createdAt:now,updatedAt:now};const r=await db.collection("tasks").insertOne(task);for(const email of av.assignees){if(email!==s.user.email)await notify(db,email,"New task assigned",`${s.user.name||s.user.email} assigned you “${p.data.title}” in ${w.name}.`,`/tasks/${r.insertedId}`)}revalidatePath(`/workspaces/${workspaceId}`);revalidatePath("/my-tasks");revalidatePath("/dashboard");return{success:true,message:"Task created successfully",taskId:r.insertedId.toString()}}catch(e){console.error(e);return{success:false,message:"Failed to create task"}}}
export async function updateTask(taskId:string,input:unknown){try{const s=await auth();if(!s?.user?.email||!ObjectId.isValid(taskId))return{success:false,message:"Invalid request"};const p=taskSchema.safeParse(input);if(!p.success)return{success:false,message:p.error.issues[0]?.message||"Invalid task data"};const db=await getDb();const current=await db.collection("tasks").findOne({_id:new ObjectId(taskId),createdBy:s.user.email});if(!current)return{success:false,message:"Task not found or you are not the owner"};const workspaceId=String((input as any)?.workspaceId||current.workspaceId?.toString()||"");const w=await workspaceFor(db,workspaceId,s.user.email);if(!w)return{success:false,message:"You are not a member of this workspace"};const currentStatus=(current.status||"todo") as Status;const nextStatus=p.data.status as Status;if(currentStatus!==nextStatus&&Math.abs(statusOrder.indexOf(currentStatus)-statusOrder.indexOf(nextStatus))!==1)return{success:false,message:"Tasks must move one stage at a time: To Do → In Progress → Completed"};const av=await validateAssignees(db,workspaceId,p.data.assignees);if(!av.success)return av;const old=new Set(Array.isArray(current.assignees)?current.assignees:(current.assignee?[current.assignee]:[]));const now=new Date();await db.collection("tasks").updateOne({_id:new ObjectId(taskId),createdBy:s.user.email},{$set:{...p.data,workspaceId:new ObjectId(workspaceId),assignees:av.assignees,tags:Array.from(new Set(p.data.tags.map(x=>x.trim()).filter(Boolean))),updatedAt:now},$unset:{assignee:""}});for(const email of av.assignees){if(!old.has(email)&&email!==s.user.email)await notify(db,email,"Task assigned to you",`${s.user.name||s.user.email} assigned you “${p.data.title}”.`,`/tasks/${taskId}`)}revalidatePath(`/tasks/${taskId}`);revalidatePath(`/workspaces/${workspaceId}`);revalidatePath("/my-tasks");return{success:true,message:"Task updated successfully"}}catch(e){console.error(e);return{success:false,message:"Failed to update task"}}}
export async function updateTaskStatus(taskId:string,status:Status){try{const s=await auth();if(!s?.user?.email||!ObjectId.isValid(taskId))return{success:false,message:"Invalid request"};if(!statusOrder.includes(status))return{success:false,message:"Invalid status"};const db=await getDb();const task=await db.collection("tasks").findOne(access(taskId,s.user.email));if(!task)return{success:false,message:"You do not have access to this task"};const current=(task.status||"todo") as Status;const from=statusOrder.indexOf(current),to=statusOrder.indexOf(status);if(Math.abs(from-to)!==1)return{success:false,message:"Tasks must move one stage at a time: To Do → In Progress → Completed"};await db.collection("tasks").updateOne(access(taskId,s.user.email),{$set:{status,updatedAt:new Date()}});revalidatePath(`/workspaces/${task.workspaceId}`);revalidatePath("/dashboard");revalidatePath("/my-tasks");return{success:true,message:"Status updated"}}catch{return{success:false,message:"Failed to update status"}}}
export async function deleteTask(taskId:string){try{const s=await auth();if(!s?.user?.email||!ObjectId.isValid(taskId))return{success:false,message:"Invalid request"};const db=await getDb();const oid=new ObjectId(taskId);const r=await db.collection("tasks").deleteOne({_id:oid,createdBy:s.user.email});if(!r.deletedCount)return{success:false,message:"Task not found or you are not the owner"};await db.collection("comments").deleteMany({taskId:oid});revalidatePath("/dashboard");revalidatePath("/my-tasks");return{success:true,message:"Task deleted successfully"}}catch{return{success:false,message:"Failed to delete task"}}}
export async function createComment(taskId:string,content:string){try{const s=await auth();if(!s?.user?.email||!ObjectId.isValid(taskId))return{success:false,message:"Invalid request"};const c=content.trim();if(c.length<1||c.length>1000)return{success:false,message:"Comment must be between 1 and 1000 characters"};const db=await getDb();const t=await db.collection("tasks").findOne(access(taskId,s.user.email));if(!t)return{success:false,message:"You do not have access to this task"};await db.collection("comments").insertOne({taskId:new ObjectId(taskId),content:c,createdBy:s.user.email,createdAt:new Date()});revalidatePath(`/tasks/${taskId}`);return{success:true,message:"Comment added"}}catch{return{success:false,message:"Failed to add comment"}}}
export async function deleteComment(commentId:string){try{const s=await auth();if(!s?.user?.email||!ObjectId.isValid(commentId))return{success:false,message:"Invalid request"};const db=await getDb();const r=await db.collection("comments").deleteOne({_id:new ObjectId(commentId),createdBy:s.user.email});return{success:r.deletedCount>0,message:r.deletedCount?"Comment deleted":"Comment not found"}}catch{return{success:false,message:"Failed to delete comment"}}}
export async function getUsersForAssignment(workspaceId?:string){try{const s=await auth();if(!s?.user?.email)return{success:false,users:[]};const db=await getDb();if(workspaceId&&ObjectId.isValid(workspaceId)){const w=await workspaceFor(db,workspaceId,s.user.email);if(!w)return{success:false,users:[]};const members=(w.members||[]).map((m:any)=>m.email);const users=await getAllUsers();return{success:true,users:users.filter(u=>members.includes(String(u.email))).map(u=>({name:String(u.name),email:String(u.email)}))}}const users=await getAllUsers();return{success:true,users:users.map(u=>({name:String(u.name),email:String(u.email)}))}}catch{return{success:false,users:[]}}}
export async function getMyTasks(){try{const s=await auth();if(!s?.user?.email)return{success:false,tasks:[]};const db=await getDb();const ws=await db.collection("workspaces").find({"members.email":s.user.email},{projection:{_id:1}}).toArray();const ids=ws.map(w=>w._id);const tasks=await db.collection("tasks").find({workspaceId:{$in:ids},$or:[{assignees:s.user.email},{assignee:s.user.email}]}).sort({createdAt:-1}).toArray();const workspaces=await db.collection("workspaces").find({_id:{$in:ids}},{projection:{name:1}}).toArray();const wm=new Map(workspaces.map(w=>[w._id.toString(),w.name]));return{success:true,tasks:tasks.map(t=>({id:t._id.toString(),title:t.title,description:t.description||"",status:t.status||"todo",priority:t.priority||"medium",dueDate:t.dueDate||null,tags:t.tags||[],assignees:t.assignees||[],createdBy:t.createdBy,createdAt:new Date(t.createdAt).toISOString(),workspaceId:t.workspaceId?.toString(),workspaceName:wm.get(t.workspaceId?.toString()||"")||"Workspace"}))}}catch{return{success:false,tasks:[]}}}
