import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ObjectId} from 'mongodb';
import {harness} from './helpers.mjs';
function setup(){const h=harness(),owner='owner@example.test',member='member@example.test',assignee='assignee@example.test',outsider='outsider@example.test';const workspaceId=new ObjectId();h.state.session={user:{email:owner,name:'Owner'}};h.state.collections.workspaces.push({_id:workspaceId,name:'Workspace',ownerEmail:owner,joinCode:'ABC123',members:[{email:owner,role:'owner'},{email:member,role:'member'},{email:assignee,role:'member'}]});for(const email of[owner,member,assignee,outsider])h.state.collections.users.push({_id:new ObjectId(),email,name:email});const task={_id:new ObjectId(),workspaceId,title:'Member task',createdBy:member,assignees:[assignee],status:'todo',priority:'medium'};h.state.collections.tasks.push(task);return{...h,owner,member,assignee,outsider,workspaceId,task,taskActions:h.load('app/actions/task.ts'),workspaceActions:h.load('app/actions/workspace.ts')};}
const input={title:'Edited task',status:'todo',priority:'medium'};
test('task deletion/editing belongs to the task creator, not automatically to the workspace owner or assignee',async()=>{const h=setup();for(const email of[h.owner,h.assignee,h.outsider]){h.state.session.user.email=email;assert.equal((await h.taskActions.deleteTask(String(h.task._id))).success,false);assert.equal((await h.taskActions.updateTask(String(h.task._id),input)).success,false)}h.state.session.user.email=h.member;assert.equal((await h.taskActions.updateTask(String(h.task._id),input)).success,true);h.state.collections.comments.push({_id:new ObjectId(),taskId:h.task._id,createdBy:h.assignee,content:'Comment'});assert.equal((await h.taskActions.deleteTask(String(h.task._id))).success,true);assert.equal(h.state.collections.comments.length,0);});
test('workspace members can create tasks; only creators/assignees change status and comment',async()=>{const h=setup();h.state.session.user.email=h.member;assert.equal((await h.taskActions.createTask({...input,workspaceId:String(h.workspaceId)})).success,true);h.state.session.user.email=h.owner;assert.equal((await h.taskActions.updateTaskStatus(String(h.task._id),'in-progress')).success,false);assert.equal((await h.taskActions.createComment(String(h.task._id),'Comment')).success,false);h.state.session.user.email=h.assignee;assert.equal((await h.taskActions.updateTaskStatus(String(h.task._id),'in-progress')).success,true);assert.equal((await h.taskActions.createComment(String(h.task._id),' Comment ')).success,true);assert.equal(h.state.collections.comments[0].content,'Comment');assert.equal((await h.taskActions.updateTaskStatus(String(h.task._id),'todo')).success,true);assert.equal((await h.taskActions.updateTaskStatus(String(h.task._id),'done')).success,false);});
test('only the comment author with current task access may delete it',async()=>{const h=setup();const comment={_id:new ObjectId(),taskId:h.task._id,createdBy:h.assignee,content:'Comment'};h.state.collections.comments.push(comment);for(const email of[h.owner,h.member,h.outsider]){h.state.session.user.email=email;assert.equal((await h.taskActions.deleteComment(String(comment._id))).success,false)}h.state.session.user.email=h.assignee;assert.equal((await h.taskActions.deleteComment(String(comment._id))).success,true);});
test('only workspace owners can edit/delete workspaces or manage members; deletion cleans child records',async()=>{const h=setup();h.state.session.user.email=h.member;assert.equal((await h.workspaceActions.updateWorkspace(String(h.workspaceId),{name:'Changed'})).success,false);assert.equal((await h.workspaceActions.deleteWorkspace(String(h.workspaceId))).success,false);assert.equal((await h.workspaceActions.addWorkspaceMember(String(h.workspaceId),h.outsider)).success,false);h.state.session.user.email=h.owner;assert.equal((await h.workspaceActions.updateWorkspace(String(h.workspaceId),{name:'Changed'})).success,true);h.state.collections.comments.push({_id:new ObjectId(),taskId:h.task._id});h.state.collections.announcements=[{_id:new ObjectId(),workspaceId:h.workspaceId}];assert.equal((await h.workspaceActions.deleteWorkspace(String(h.workspaceId))).success,true);for(const name of['workspaces','tasks','comments','announcements'])assert.equal(h.state.collections[name].length,0);});
test('joins/add-member reject duplicates and owner removal is denied',async()=>{const h=setup();h.state.session.user.email=h.outsider;assert.equal((await h.workspaceActions.joinWorkspace(' abc123 ')).success,true);assert.equal((await h.workspaceActions.joinWorkspace('ABC123')).success,false);assert.equal(h.state.collections.workspaces[0].members.filter(m=>m.email===h.outsider).length,1);h.state.session.user.email=h.owner;assert.equal((await h.workspaceActions.addWorkspaceMember(String(h.workspaceId),h.outsider)).success,false);assert.equal((await h.workspaceActions.removeWorkspaceMember(String(h.workspaceId),h.owner)).success,false);assert.equal((await h.workspaceActions.removeWorkspaceMember(String(h.workspaceId),h.assignee)).success,true);assert.deepEqual(h.task.assignees,[]);});
test('all write paths reject invalid content, dates, assignees, emails, and join codes',async()=>{const h=setup();for(const bad of[{title:'   '},{title:'x'.repeat(101)},{description:'x'.repeat(2001)},{status:'invalid'},{priority:'urgent'},{startDate:'2026-10-12',dueDate:'2026-10-10'},{dueDate:'2026-02-30'},{tags:['x'.repeat(31)]},{assignees:[h.outsider]}])assert.equal((await h.taskActions.createTask({...input,workspaceId:String(h.workspaceId),...bad})).success,false);for(const bad of[{name:' '},{name:'A'},{name:'x'.repeat(81)},{name:'Good',description:'x'.repeat(301)}])assert.equal((await h.workspaceActions.createWorkspace(bad)).success,false);assert.equal((await h.workspaceActions.addWorkspaceMember(String(h.workspaceId),'not-an-email')).success,false);for(const code of['','123','1234567','!!!!!!',null])assert.equal((await h.workspaceActions.joinWorkspace(code)).success,false);h.state.session.user.email=h.member;for(const text of['','   ','x'.repeat(1001),null])assert.equal((await h.taskActions.createComment(String(h.task._id),text)).success,false);assert.equal(h.state.writes.length,0);});
