"use client";
import Link from "next/link";import { signIn } from "next-auth/react";import { useState } from "react";import { Moon,Sun,Sparkles } from "@/components/icons";import { loginSchema } from "@/lib/validations/auth";import { useTheme } from "@/components/ThemeProvider";
export default function LoginPage(){const {theme,toggle}=useTheme();const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:React.FormEvent){
 e.preventDefault();if(loading)return;setError("");
 const parsed=loginSchema.safeParse({email,password});
 if(!parsed.success){setError(parsed.error.issues[0].message);return}
 setLoading(true);
 try{
  const r=await signIn("credentials",{...parsed.data,redirect:false,redirectTo:"/dashboard"});
  if(!r?.ok||r.error){setError(r?.error==="CredentialsSignin"?"Invalid email or password":"Unable to sign in. Please try again.");return}
  // A fresh navigation clears any prefetched data from an earlier account.
  window.location.replace("/dashboard");
 }catch{setError("Unable to sign in. Check your connection and try again.")}
 finally{setLoading(false)}
}return <main className="auth-page"><section className="auth-visual"><div className="max-w-xl"><div className="auth-logo"><div className="brand-mark"><Sparkles size={18}/></div><div><div className="text-lg font-extrabold">TaskFlow</div><div className="text-xs text-white/60">Work, organized.</div></div></div><p className="text-sm font-semibold text-indigo-200">A calmer way to manage team work</p><h1 className="mt-3 text-5xl font-black leading-[1.02] tracking-[-.05em]">Turn scattered tasks into visible progress.</h1><p className="mt-5 max-w-lg text-sm leading-7 text-white/65">Create workspaces, assign tasks, collaborate in context, and move work through a clear delivery flow.</p><div className="auth-feature"><Feature title="Private workspaces" text="Keep tasks and members in the right project context."/><Feature title="Assignment notifications" text="Know immediately when work lands in your queue."/><Feature title="Drag-and-drop Kanban" text="Move work one stage at a time from To Do to Completed."/></div></div></section><section className="auth-card-wrap"><div className="auth-card"><div className="flex justify-end"><button className="theme-toggle" aria-label={`Switch to ${theme==="light"?"dark":"light"} mode`} onClick={toggle}>{theme==="light"?<Moon size={17}/>:<Sun size={17}/>}</button></div><div className="auth-logo mt-4"><div className="brand-mark"><Sparkles size={17}/></div><div><div className="text-base font-extrabold">Welcome back</div><div className="text-xs muted">Sign in to your workspace</div></div></div><form onSubmit={submit} className="mt-8 space-y-4"><div><label className="label" htmlFor="app-login-page-email">Email *</label><input id="app-login-page-email" className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com" autoComplete="email"/></div><div><label className="label" htmlFor="app-login-page-password">Password *</label><input id="app-login-page-password" className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Your password" autoComplete="current-password"/></div>{error&&<div role="alert" className="rounded-lg bg-rose-500/10 p-3 text-xs text-rose-500">{error}</div>}<button className="button button-primary w-full" disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form><p className="mt-5 text-center text-xs muted">New to TaskFlow? <Link className="font-bold text-[var(--primary)]" href="/signup">Create an account</Link></p></div></section></main>}
function Feature({title,text}:{title:string;text:string}){return <div className="feature"><div className="feature-icon"><Sparkles size={15}/></div><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">{text}</p></div></div>}
