"use client";
import Link from "next/link";import { useState } from "react";import { useRouter } from "next/navigation";import { Moon,Sun,Sparkles,Check } from "@/components/icons";import { registrationSchema } from "@/lib/validations/auth";import { useTheme } from "@/components/ThemeProvider";
export default function SignupPage(){const router=useRouter();const {theme,toggle}=useTheme();const [name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:React.FormEvent){
 e.preventDefault();if(loading)return;setError("");
 const parsed=registrationSchema.safeParse({name,email,password});
 if(!parsed.success){setError(parsed.error.issues[0].message);return}
 setLoading(true);
 try{
  const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(parsed.data)});
  const data=await r.json();
  if(!r.ok||!data.success){setError(data.message||"Registration failed");return}
  setPassword("");router.replace("/login");
 }catch{setError("Unable to register. Check your connection and try again.")}
 finally{setLoading(false)}
};return <main className="auth-page"><section className="auth-visual"><div className="max-w-xl"><div className="auth-logo"><div className="brand-mark"><Sparkles size={18}/></div><div><div className="text-lg font-extrabold">TaskFlow</div><div className="text-xs text-white/60">Work, organized.</div></div></div><p className="text-sm font-semibold text-indigo-200">Build a home for your team</p><h1 className="mt-3 text-5xl font-black leading-[1.02] tracking-[-.05em]">One workspace for the work that matters.</h1><div className="auth-feature"><Feature text="Create private workspaces with shareable join codes."/><Feature text="Add members and assign tasks from a workspace-only dropdown."/><Feature text="Get notifications when work is assigned to you."/></div></div></section><section className="auth-card-wrap"><div className="auth-card"><div className="flex justify-end"><button className="theme-toggle" aria-label={`Switch to ${theme==="light"?"dark":"light"} mode`} onClick={toggle}>{theme==="light"?<Moon size={17}/>:<Sun size={17}/>}</button></div><div className="auth-logo mt-4"><div className="brand-mark"><Sparkles size={17}/></div><div><div className="text-base font-extrabold">Create your account</div><div className="text-xs muted">Set up your TaskFlow identity</div></div></div><form onSubmit={submit} className="mt-8 space-y-4"><div><label className="label" htmlFor="app-signup-page-full-name">Full name *</label><input id="app-signup-page-full-name" className="input" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={80} placeholder="Your name" autoComplete="name"/></div><div><label className="label" htmlFor="app-signup-page-email">Email *</label><input id="app-signup-page-email" className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} placeholder="you@example.com" autoComplete="email"/></div><div><label className="label" htmlFor="app-signup-page-password">Password *</label><input id="app-signup-page-password" className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} maxLength={128} placeholder="At least 6 characters" autoComplete="new-password"/></div>{error&&<div role="alert" className="rounded-lg bg-rose-500/10 p-3 text-xs text-rose-500">{error}</div>}<button className="button button-primary w-full" disabled={loading}>{loading?"Creating…":<><Check size={15}/> Create account</>}</button></form><p className="mt-5 text-center text-xs muted">Already have an account? <Link className="font-bold text-[var(--primary)]" href="/login">Sign in</Link></p></div></section></main>}
function Feature({text}:{text:string}){return <div className="feature"><div className="feature-icon"><Check size={15}/></div><p className="text-sm leading-6 text-white/75">{text}</p></div>}
